<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.git.hui.springai</groupId>
        <artifactId>spring-ai-demo</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>com.git.hui.springai.app</groupId>
    <artifactId>advance-projects</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>A02-memory-jdbc-h2</module>
        <module>A02-memory-jdbc-h2-zfd</module>
        <module>A01-memory-jdbc-mysql</module>
        <module>A01-memory-jdbc-mysql-zfd</module>
        <module>A03-memory-redis</module>
        <module>A04-memory-agent-langgraph</module>
        <module>A04-memory-agent-langgraph-zfd</module>
        <module>A05-agent-langgraph-simple</module>
        <module>A05-agent-langgraph-simple-zfd</module>
        <module>A06-ReAct-agent</module>
        <module>A06-ReAct-agent-zfd</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>