spring:
  ai:
    zhipuai:
      # api-key 使用你自己申请的进行替换；如果为了安全考虑，可以通过启动参数进行设置
      api-key: ${zhipuai-api-key:f6c186238144497fbce69ea4b7e108df.UiZZhrHj6BTMIg8Q}
      chat:
        options:
          model: GLM-4-Flash