<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.git.hui.springai</groupId>
        <artifactId>spring-ai-demo</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>com.git.hui.springai.ali</groupId>
    <artifactId>ali</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>L01-simple-demo</module>
        <module>L01-simple-demo-zfd</module>
        <module>L02-human-in-loop</module>
        <module>L02-human-in-loop-zfd</module>
        <module>L03-skill-creator</module>
        <module>L03-skill-creator-zfd</module>
        <module>L04-handsoff</module>
        <module>L04-handsoff-zfd</module>
        <module>L05-multi-agent-sequence</module>
        <module>L05-multi-agent-sequence-zfd</module>
        <module>L06-multi-agent-paralle</module>
        <module>L07-multi-agent-route</module>
        <module>L08-multi-agent-supervisor</module>
        <module>L09-sub-agent</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <ali-version>1.1.2.2</ali-version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-agent-framework</artifactId>
            <version>${ali-version}</version>
        </dependency>
    </dependencies>

</project>