spring:
  ai:
    openai:
      # api-key 使用你自己申请的进行替换；如果为了安全考虑，可以通过启动参数进行设置
      api-key: ${spark-api-key:MKuYFqlpPeCskEmmRznt:vLHXovJgQOTPGuhUToID}
      chat: # 聊天模型
        options:
          model: lite
      base-url: https://spark-api-open.xf-yun.com

# 修改日志级别
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug