spring:
  ai:
    openai:
      # api-key 使用你自己申请的进行替换；如果为了安全考虑，可以通过启动参数进行设置
      api-key: ${api-key}
      chat: # 聊天模型
        options:
          # model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B # 不支持工具调用
          # model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
          # model: THUDM/GLM-Z1-9B-0414
          # model: THUDM/GLM-4-9B-0414
          # model: THUDM/glm-4-9b-chat # 不支持工具调用
#          model: Qwen/Qwen2.5-7B-Instruct
           model: Qwen/Qwen3-8B
      base-url: https://api.siliconflow.cn

    zhipuai:
      api-key: ${zhipuai-api-key}
      chat:
        options:
          model: GLM-4-Flash

  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  tomcat:
    uri-encoding: UTF-8
