<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.git.hui.springai.app</groupId>
        <artifactId>advance-projects</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>com.git.hui.springai.advance</groupId>
    <artifactId>A03-memory-redis</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-zhipuai</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-chat-memory</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </dependency>
<!--        https://github.com/zhoufudun/redis-mock   自己下载打包-->
        <dependency>
            <groupId>com.github.microwww</groupId>
            <artifactId>redis-server</artifactId>
            <version>0.3.6</version>
<!--            <scope>test</scope>-->
        </dependency>
<!--        https://github.com/zhoufudun/redis-mock  自己下载打包-->
        <dependency>
            <groupId>com.github.microwww</groupId>
            <artifactId>mocker-redis-spring-boot-starter</artifactId>
            <version>5.3.0</version>
        </dependency>
    </dependencies>

</project>